### ISSUE TITLE
Using source code of personal website

### ISSUE THREAD

**Issue by marksanghoonkim** [heiswayi/ama#1]
Hi Heiswayi!

I stumbled upon your Plain Jekyll theme and love it! And then I stumbled upon your website and I love it even more!! I am trying to set up my own personal blog/projects website and was wondering if I could use parts of your personal website. I am just looking to add to the Plain template the social links and possibly another section under the blog posts for project info and links.

Great work, and I love the simple, clean look of your sites. Awesome!

Best,
Mark

**Comment by heiswayi** [comment]
As I mentioned in the footer of [my website](http://heiswayi.github.io):
> Unless otherwise stated, all original code presented on this site is licensed under the **MIT license**. All original photographs and text on this website are licensed under a **Creative Commons Attribution-NonCommercial-NoDerivatives license**. If you have any questions about using any of this material for commercial purposes, please ask me here or write an email to me.

The source code is released under [MIT license](https://github.com/heiswayi/heiswayi.github.io/blob/master/LICENSE.md), feel free to do whatever you want.
